In [1]:
import numpy as np
import tensorflow as tf
from kmeseg import Tokenizer
from kmeseg.core.tokenize import Segmentation


In [2]:
kme_segment = Segmentation()
tokenizer = Tokenizer()

OSError: SavedModel file does not exist at: /root/git-projects/KME-WordSegmentation/notebooks/models/save_model/kmeseg_model.h5/{saved_model.pbtxt|saved_model.pb}

In [ ]:
text = 'cyclohexanoic acid'
x_test = kme_segment.preprocessing_text(text)
print(x_test.shape)

(18, 10)


In [ ]:
predict = kme_segment.predict(x_test)

pred_text, pred_text_join = kme_segment.word_segmentation(text)

print(predict)
print(pred_text)
print(pred_text_join)

2021-11-08 14:13:05.336367: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2021-11-08 14:13:06.767213: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8204


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
['cyclohexanoic acid']
cyclohexanoic acid


In [ ]:
text_arr = ['methyl methanoate', 'ethane', '(hydroxymethylamino)oxy-methoxymethanol']
for item in text_arr:
    word, _ = kme_segment.word_segmentation(item)
    print(word)

['methyl methanoate']
['ethane']
['(hydroxymethylamino)oxy-methoxymethanol']


In [ ]:
text_arr = ['methyl methanoate', 'ethane', '(hydroxymethylamino)oxy-methoxymethanol']

tokenizer.fit_on_texts(text_arr)

train_seq = tokenizer.text_to_sequences(text_arr, method_pad='pre')
print(train_seq)

100%|██████████| 3/3 [00:00<00:00, 14.97it/s]

[[1 4 2]
 [1 5 2]
 [1 6 2]]


In [ ]:
print(tokenizer.word2index)

{'<pad>': 0, '<start>': 1, '<end>': 2, '<unk>': 3, 'methyl methanoate': 4, 'ethane': 5, '(hydroxymethylamino)oxy-methoxymethanol': 6}


In [ ]:
print(tokenizer.word2count)

{'<pad>': 0, '<start>': 3, '<end>': 3, '<unk>': 0, 'methyl methanoate': 1, 'ethane': 1, '(hydroxymethylamino)oxy-methoxymethanol': 1}


In [ ]:
test_arr = ['2-(4-methoxyphenyl)-2-oxoacetic acid']

test_seq = tokenizer.text_to_sequences(test_arr)
print(test_seq)

test_text = tokenizer.sequences_to_text(test_seq)
print(test_text)

100%|██████████| 1/1 [00:00<00:00,  2.79it/s]


[[1 3 2]]


100%|██████████| 1/1 [00:00<00:00, 8019.70it/s]

[['<start>' '<unk>' '<end>']]
